#!/bin/bash

qwen_path=../model_path/qwen2
qwen_save_path=../model_save/qwen2_16bit_pretrain/best_val_acc_model/


# Process Post-pretrain& Finetune Data
sh run_data.sh

# Run Post-pretrain
sh run_post_pretrain_ut_three_model.sh

python3 PreSafeTensor2bin.py --model_path ${qwen_path} --safe_lora_path ${qwen_save_path}

# Run Finetune with Post-pretrained weights and 3*Distil Data generated by 3 teacher models
sh run_pipeline.sh 0
sh run_pipeline.sh 1
sh run_pipeline.sh 2
sh run_pipeline.sh 3
sh run_pipeline.sh 4

# # Merge 5 fold weights
# python3 merge_weights.py
# cp ../model_save/qwen2_16bit_load_fintune/fold0/kl_distil4_encode/1best_val_acc_model/adapter_config.json ../model_save/temp-merge

# python3 run_gptq.py

# # Run Inference Code
# python3 wsdm_inference.py